[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/defx.nvim'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'Lokaltog/vim-easymotion'
hook_add = '''
  " デフォルトのキーマッピングを無効に
    let g:EasyMotion_do_mapping = 0
  " f + 2文字 で画面全体を検索してジャンプ
    nmap f <plug>(easymotion-overwin-f2)
  " 検索時、大文字小文字を区別しない
    let g:EasyMotion_smartcase = 1
'''
